### ISSUE TITLE
How can I buy the controller?

### ISSUE THREAD

**Issue by LuPeNGaMeS** [SE-Nexus/SE-Nexus.github.io#1]
Hello, I have been looking for how to acquire the nexus driver, whatever version it is, but I can't find it anywhere and the community doesn't know much either.

I see they are making a new version of Nexus. Something that excites me! Thank you very much for making life easier for us Space Engineers server administrators.

Is there a way to purchase a Nexus license?

Thanks for your response in advance!

**Comment by austinvaness** [comment]
The controller will be available for purchase starting Friday. Join us for the launch event on the [discord server](https://discord.gg/fJbwebvTWU) for more information.
